#!/usr/bin/env python3
"""
Prototype: counts -> CBD scenario demand.

A thin orchestrator around the project's existing, calibrated demand generator
(``sumo_demand_from_traffic_csv.py``, which places turning counts onto the CBD
network's edge graph). This wrapper only *selects inputs and wires outputs* — it
does not re-implement any traffic modelling:

  1. (optional) slice a parsed counts CSV to one survey date,
  2. run the demand generator (optionally AM/PM) -> scenarios/<name>.rou.xml,
  3. write scenarios/<name>.sumocfg pointing the CBD network at that demand.

You then play it with run_traci.py. The generator lays counts out from t=0 —
either "stacked" (slots packed into consecutive windows; the default) or
"calendar" (--timeline calendar: slots keep their real time gaps, still anchored
at t=0). Either way, run the scenario with ``--jump-to 0`` (not the default
06:30 jump):

    python scripts/make_cbd_scenario.py --name am_2020 --survey-date 2020-02-17 --period AM
    python scripts/run_traci.py --sumocfg scenarios/am_2020.sumocfg --no-gui --emit --jump-to 0

Needs the plain-edges graph (data/output/network/sumo_plain_edges.edg.xml), which
exists on a machine that has built the network — i.e. run this on the VM/Mac, not
in a bare checkout.

Caveat: turning-count -> route demand is an estimation (inherent to the method).
This produces an approximate, CBD-scoped scenario for comparison, not a
ground-truth reconstruction.
"""
from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from pathlib import Path

from _sim_root import DEMAND_DIR, NETWORK_DIR, SIM_ROOT  # noqa: E402

SCRIPTS_DIR = Path(__file__).resolve().parent
SCENARIOS_DIR = SIM_ROOT / "scenarios"
# The counts-derived demand rides on the INTERSECTION-GRAPH network built by
# sumo_network_from_geo.py (edge ids "e_<from>_<to>", node ids = intersection_id),
# NOT the calibrated street net — those edge ids don't exist there. Likewise there
# is no matching .add.xml (the street net's detectors/TLS are keyed to street lanes).
NET_NAME = "christchurch_intersections.net.xml"
DEFAULT_CSV = DEMAND_DIR / "traffic_18MAY2026_130842.csv"

_EDGES_HELP = (
    "The demand generator needs the INTERSECTION-GRAPH edges file\n"
    "  data/output/network/sumo_plain_edges.edg.xml\n"
    "whose node ids are the counts' intersection_id. This is produced by the\n"
    "network build (scripts/sumo_network_from_geo.py, after\n"
    "fill_intersection_direction_neighbours.py), NOT by reverse-exporting the\n"
    "compiled .net.xml — netconvert renames/merges junctions, so its node ids\n"
    "won't match the counts (symptom: 'Skipped (endpoint not in network)' for\n"
    "every row, 0 vehicles). Regenerate via the from-geo build, then re-run this."
)

_SUMOCFG = """<?xml version='1.0' encoding='UTF-8'?>
<!-- CBD scenario generated by make_cbd_scenario.py from CCC intersection counts.
     Demand is laid out from t=0, so run it with run_traci.py using jump-to 0. -->
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="../data/output/network/{net}" />
        <route-files value="{routes}" />
    </input>
    <time>
        <begin value="0" />
        <end value="86400" />
        <step-length value="1" />
    </time>
</sumoConfiguration>
"""


def filter_csv(
    src: Path,
    dst: Path,
    *,
    survey_date: str | None = None,
    start_time: str | None = None,
    end_time: str | None = None,
) -> int:
    """Write rows of ``src`` matching the given filters to ``dst``; return rows kept.

    ``survey_date`` keeps rows whose survey_date starts with it (YYYY-MM-DD).
    ``start_time``/``end_time`` keep rows whose ``time`` slot is in the half-open
    window [start, end) — e.g. 09:00..11:00 keeps the 09:00..10:45 slots (each 15-min
    slot is labelled by its start), matching "9AM to 11AM". Times are zero-padded
    HH:MM, so plain string comparison is correct. Pure file I/O — testable without
    SUMO or the network.
    """
    with src.open(newline="") as fin, dst.open("w", newline="") as fout:
        reader = csv.DictReader(fin)
        fn = reader.fieldnames
        if fn is None or "survey_date" not in fn:
            raise ValueError("CSV has no 'survey_date' column")
        if (start_time or end_time) and "time" not in fn:
            raise ValueError("CSV has no 'time' column — cannot filter by time window")
        writer = csv.DictWriter(fout, fieldnames=fn)
        writer.writeheader()
        kept = 0
        for row in reader:
            if survey_date and not (row.get("survey_date") or "").strip().startswith(survey_date):
                continue
            if start_time or end_time:
                t = (row.get("time") or "").strip()
                if not t:
                    continue
                if start_time and t < start_time:
                    continue
                if end_time and t >= end_time:
                    continue
            writer.writerow(row)
            kept += 1
    return kept


def filter_csv_by_date(src: Path, dst: Path, survey_date: str) -> int:
    """Back-compat wrapper: slice ``src`` to one survey date. See ``filter_csv``."""
    return filter_csv(src, dst, survey_date=survey_date)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a CBD scenario demand from CCC counts.")
    ap.add_argument("--name", required=True, help="Scenario name (used for the output filenames).")
    ap.add_argument("--traffic-csv", type=Path, default=DEFAULT_CSV,
                    help=f"Parsed counts CSV (default: {DEFAULT_CSV.name}).")
    ap.add_argument("--from-etl-date", default=None,
                    help="Fetch this survey date's counts from the ETL store (S3) instead of "
                         "using --traffic-csv. Needs --etl-bucket (or ETL_DATA_BUCKET) and AWS creds.")
    ap.add_argument("--etl-bucket", default=None,
                    help="ETL data bucket for --from-etl-date (or set ETL_DATA_BUCKET). "
                         "terraform output etl_data_bucket.")
    ap.add_argument("--survey-date", default=None,
                    help="Keep only this survey date (YYYY-MM-DD); default: all dates in the CSV.")
    ap.add_argument("--period", choices=("AM", "PM", "ALL"), default="ALL",
                    help="Coarse time-of-day bucket to keep (default: ALL). For an exact "
                         "window use --start-time/--end-time instead.")
    ap.add_argument("--start-time", default=None,
                    help="Keep only count slots at or after this time (HH:MM, e.g. 09:00).")
    ap.add_argument("--end-time", default=None,
                    help="Keep only count slots before this time (HH:MM, e.g. 11:00). "
                         "The window is half-open [start, end): 09:00..11:00 = the 9-11AM slots.")
    ap.add_argument("--min-count", type=int, default=1, help="Drop count groups below this (default: 1).")
    ap.add_argument("--timeline", choices=("stacked", "calendar"), default="stacked",
                    help="How count slots map to sim time (passed to the demand generator). "
                         "stacked (default): slots packed into consecutive windows from t=0. "
                         "calendar: slots keep their real time gaps (still anchored at t=0, "
                         "i.e. seconds since the earliest slot). Either way, play with --jump-to 0.")
    args = ap.parse_args()

    SCENARIOS_DIR.mkdir(parents=True, exist_ok=True)
    routes_path = SCENARIOS_DIR / f"{args.name}.rou.xml"
    sumocfg_path = SCENARIOS_DIR / f"{args.name}.sumocfg"

    # 0. optionally pull the counts for one date straight from the ETL store (S3).
    #    Lazy import so boto3/S3 is only required when this path is used.
    if args.from_etl_date:
        import os
        from etl.s3_store import S3ObjectStore
        from etl.scenario_bridge import build_counts_csv_for_date
        bucket = args.etl_bucket or os.environ.get("ETL_DATA_BUCKET")
        if not bucket:
            print("Error: --from-etl-date needs --etl-bucket or ETL_DATA_BUCKET "
                  "(terraform output etl_data_bucket).", file=sys.stderr)
            return 2
        etl_csv = SCENARIOS_DIR / f"{args.name}.etl.csv"
        summary = build_counts_csv_for_date(S3ObjectStore(bucket), args.from_etl_date, etl_csv)
        if summary["rows"] == 0:
            print(f"Error: no ETL counts for {args.from_etl_date} in s3://{bucket}. "
                  f"Has the ETL ingested this date? (Only surveyed days exist.)", file=sys.stderr)
            return 1
        slots = summary["time_slots"]
        print(f"fetched {summary['rows']} rows / {summary['intersections']} intersections for "
              f"{args.from_etl_date} (slots {slots[0]}..{slots[-1]}) -> {etl_csv.name}")
        args.traffic_csv = etl_csv

    if not args.traffic_csv.is_file():
        print(f"Error: counts CSV not found: {args.traffic_csv}", file=sys.stderr)
        return 1

    # 1. optionally slice by survey date and/or time-of-day window
    csv_in = args.traffic_csv
    if args.survey_date or args.start_time or args.end_time:
        sliced = SCENARIOS_DIR / f"{args.name}.counts.csv"
        kept = filter_csv(
            args.traffic_csv, sliced,
            survey_date=args.survey_date,
            start_time=args.start_time,
            end_time=args.end_time,
        )
        crit = ", ".join(
            p for p in (
                f"date={args.survey_date}" if args.survey_date else "",
                f"time>={args.start_time}" if args.start_time else "",
                f"time<{args.end_time}" if args.end_time else "",
            ) if p
        )
        if kept == 0:
            print(f"Error: no rows matching [{crit}] in {args.traffic_csv.name}. "
                  f"Note the data covers 2016-01..2025-08 (45 survey days) and 06:30-18:15 slots.",
                  file=sys.stderr)
            return 1
        print(f"sliced {kept} rows for [{crit}] -> {sliced.name}")
        csv_in = sliced

    # 2. run the existing demand generator
    cmd = [
        sys.executable, str(SCRIPTS_DIR / "sumo_demand_from_traffic_csv.py"),
        "--traffic-csv", str(csv_in),
        "--output", str(routes_path),
        "--period", args.period,
        "--min-count", str(args.min_count),
        "--timeline", args.timeline,
    ]
    edges_xml = NETWORK_DIR / "sumo_plain_edges.edg.xml"
    if not edges_xml.is_file():
        print(_EDGES_HELP, file=sys.stderr)
        return 1

    print("running:", " ".join(cmd))
    result = subprocess.run(cmd, text=True, capture_output=True)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        print("demand generation failed.", file=sys.stderr)
        return result.returncode

    # Empty demand almost always means the edges file's node ids don't match the
    # counts' intersection_id (e.g. a netconvert reverse-export instead of the
    # intersection-graph edges). Fail loudly instead of writing a useless sumocfg.
    if "Total vehicles (number sum): 0" in result.stdout:
        print(_EDGES_HELP, file=sys.stderr)
        return 2

    # 3. write the scenario sumocfg
    net_xml = NETWORK_DIR / NET_NAME
    if not net_xml.is_file():
        print(f"warning: {NET_NAME} not found in data/output/network/ — the scenario\n"
              f"  needs the compiled intersection net. Run sumo_network_from_geo.py WITHOUT\n"
              f"  --no-netconvert (it produces {NET_NAME}) before playing this scenario.",
              file=sys.stderr)
    sumocfg_path.write_text(
        _SUMOCFG.format(net=NET_NAME, routes=routes_path.name), encoding="utf-8"
    )
    print(f"wrote {routes_path.name} + {sumocfg_path.name}")
    print("\nplay it (demand starts at t=0, so --jump-to 0):")
    print(f"  python scripts/run_traci.py --sumocfg scenarios/{sumocfg_path.name} "
          f"--no-gui --emit --real-time --jump-to 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
