#!/usr/bin/env python3
"""
Prototype: counts -> CBD scenario demand.

A thin orchestrator around the project's existing, calibrated demand generator
(``sumo_demand_from_traffic_csv.py``, which places turning counts onto the CBD
network's edge graph). This wrapper only *selects inputs and wires outputs* — it
does not re-implement any traffic modelling:

  1. (optional) slice a parsed counts CSV to one survey date,
  2. run the demand generator (optionally AM/PM) -> scenarios/<name>.rou.xml,
  3. write scenarios/<name>.sumocfg pointing the CBD network at that demand.

You then play it with run_traci.py. The generator lays counts out from t=0 —
either "stacked" (slots packed into consecutive windows; the default) or
"calendar" (--timeline calendar: slots keep their real time gaps, still anchored
at t=0). Either way, run the scenario with ``--jump-to 0`` (not the default
06:30 jump):

    python scripts/make_cbd_scenario.py --name am_2020 --survey-date 2020-02-17 --period AM
    python scripts/run_traci.py --sumocfg scenarios/am_2020.sumocfg --no-gui --emit --jump-to 0

Needs the plain-edges graph (data/output/network/sumo_plain_edges.edg.xml), which
exists on a machine that has built the network — i.e. run this on the VM/Mac, not
in a bare checkout.

Caveat: turning-count -> route demand is an estimation (inherent to the method).
This produces an approximate, CBD-scoped scenario for comparison, not a
ground-truth reconstruction.
"""
from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from pathlib import Path

from _sim_root import DEMAND_DIR, NETWORK_DIR, SIM_ROOT  # noqa: E402

SCRIPTS_DIR = Path(__file__).resolve().parent
SCENARIOS_DIR = SIM_ROOT / "scenarios"
# The counts-derived demand rides on the INTERSECTION-GRAPH network built by
# sumo_network_from_geo.py (edge ids "e_<from>_<to>", node ids = intersection_id),
# NOT the calibrated street net — those edge ids don't exist there. Likewise there
# is no matching .add.xml (the street net's detectors/TLS are keyed to street lanes).
NET_NAME = "christchurch_intersections.net.xml"
DEFAULT_CSV = DEMAND_DIR / "traffic_18MAY2026_130842.csv"

_EDGES_HELP = (
    "The demand generator needs the INTERSECTION-GRAPH edges file\n"
    "  data/output/network/sumo_plain_edges.edg.xml\n"
    "whose node ids are the counts' intersection_id. This is produced by the\n"
    "network build (scripts/sumo_network_from_geo.py, after\n"
    "fill_intersection_direction_neighbours.py), NOT by reverse-exporting the\n"
    "compiled .net.xml — netconvert renames/merges junctions, so its node ids\n"
    "won't match the counts (symptom: 'Skipped (endpoint not in network)' for\n"
    "every row, 0 vehicles). Regenerate via the from-geo build, then re-run this."
)

_SUMOCFG = """<?xml version='1.0' encoding='UTF-8'?>
<!-- CBD scenario generated by make_cbd_scenario.py from CCC intersection counts.
     Demand is laid out from t=0, so run it with run_traci.py using jump-to 0. -->
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="../data/output/network/{net}" />
        <route-files value="{routes}" />
    </input>
    <time>
        <begin value="0" />
        <end value="86400" />
        <step-length value="1" />
    </time>
</sumoConfiguration>
"""


def filter_csv_by_date(src: Path, dst: Path, survey_date: str) -> int:
    """Write rows of ``src`` whose survey_date matches ``survey_date`` to ``dst``.

    Returns the number of data rows kept. Pure file I/O, so it's testable without
    SUMO or the network.
    """
    with src.open(newline="") as fin, dst.open("w", newline="") as fout:
        reader = csv.DictReader(fin)
        if reader.fieldnames is None or "survey_date" not in reader.fieldnames:
            raise ValueError("CSV has no 'survey_date' column")
        writer = csv.DictWriter(fout, fieldnames=reader.fieldnames)
        writer.writeheader()
        kept = 0
        for row in reader:
            if (row.get("survey_date") or "").strip().startswith(survey_date):
                writer.writerow(row)
                kept += 1
    return kept


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a CBD scenario demand from CCC counts.")
    ap.add_argument("--name", required=True, help="Scenario name (used for the output filenames).")
    ap.add_argument("--traffic-csv", type=Path, default=DEFAULT_CSV,
                    help=f"Parsed counts CSV (default: {DEFAULT_CSV.name}).")
    ap.add_argument("--survey-date", default=None,
                    help="Keep only this survey date (YYYY-MM-DD); default: all dates in the CSV.")
    ap.add_argument("--period", choices=("AM", "PM", "ALL"), default="ALL",
                    help="Time-of-day bucket to keep (default: ALL).")
    ap.add_argument("--min-count", type=int, default=1, help="Drop count groups below this (default: 1).")
    ap.add_argument("--timeline", choices=("stacked", "calendar"), default="stacked",
                    help="How count slots map to sim time (passed to the demand generator). "
                         "stacked (default): slots packed into consecutive windows from t=0. "
                         "calendar: slots keep their real time gaps (still anchored at t=0, "
                         "i.e. seconds since the earliest slot). Either way, play with --jump-to 0.")
    args = ap.parse_args()

    if not args.traffic_csv.is_file():
        print(f"Error: counts CSV not found: {args.traffic_csv}", file=sys.stderr)
        return 1

    SCENARIOS_DIR.mkdir(parents=True, exist_ok=True)
    routes_path = SCENARIOS_DIR / f"{args.name}.rou.xml"
    sumocfg_path = SCENARIOS_DIR / f"{args.name}.sumocfg"

    # 1. optionally slice to one survey date
    csv_in = args.traffic_csv
    if args.survey_date:
        sliced = SCENARIOS_DIR / f"{args.name}.counts.csv"
        kept = filter_csv_by_date(args.traffic_csv, sliced, args.survey_date)
        if kept == 0:
            print(f"Error: no rows for survey_date {args.survey_date} in {args.traffic_csv.name}",
                  file=sys.stderr)
            return 1
        print(f"sliced {kept} rows for {args.survey_date} -> {sliced.name}")
        csv_in = sliced

    # 2. run the existing demand generator
    cmd = [
        sys.executable, str(SCRIPTS_DIR / "sumo_demand_from_traffic_csv.py"),
        "--traffic-csv", str(csv_in),
        "--output", str(routes_path),
        "--period", args.period,
        "--min-count", str(args.min_count),
        "--timeline", args.timeline,
    ]
    edges_xml = NETWORK_DIR / "sumo_plain_edges.edg.xml"
    if not edges_xml.is_file():
        print(_EDGES_HELP, file=sys.stderr)
        return 1

    print("running:", " ".join(cmd))
    result = subprocess.run(cmd, text=True, capture_output=True)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        print("demand generation failed.", file=sys.stderr)
        return result.returncode

    # Empty demand almost always means the edges file's node ids don't match the
    # counts' intersection_id (e.g. a netconvert reverse-export instead of the
    # intersection-graph edges). Fail loudly instead of writing a useless sumocfg.
    if "Total vehicles (number sum): 0" in result.stdout:
        print(_EDGES_HELP, file=sys.stderr)
        return 2

    # 3. write the scenario sumocfg
    net_xml = NETWORK_DIR / NET_NAME
    if not net_xml.is_file():
        print(f"warning: {NET_NAME} not found in data/output/network/ — the scenario\n"
              f"  needs the compiled intersection net. Run sumo_network_from_geo.py WITHOUT\n"
              f"  --no-netconvert (it produces {NET_NAME}) before playing this scenario.",
              file=sys.stderr)
    sumocfg_path.write_text(
        _SUMOCFG.format(net=NET_NAME, routes=routes_path.name), encoding="utf-8"
    )
    print(f"wrote {routes_path.name} + {sumocfg_path.name}")
    print("\nplay it (demand starts at t=0, so --jump-to 0):")
    print(f"  python scripts/run_traci.py --sumocfg scenarios/{sumocfg_path.name} "
          f"--no-gui --emit --real-time --jump-to 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
